name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t etenity/react -f Dockerfile.dev .
      - run: docker run -e CI=true etenity/react npm test
      - run: docker build -t etenity/react-prod -f Dockerfile .
      - run: docker push etenity/react-prod

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker
          environment_name: docker-env
          region: us-east-1
          version_label: ${{ github.sha }}
          image_name: etenity/react-prod
